# map category name to icon
categoryIcon:
  "Database & Cache": "database"
  "Prometheus Exporter": "export"
  "Networking": "router"
  "Storage": "storage"
  "Image Registry": "cdn"
  "Big Data": "increase"
  "Message Queueing": "blockchain"
  "Web Server": "ip"
