apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: openpitrix
    component: openpitrix-upgrade-job
  name: openpitrix-upgrade-job
  namespace: d3os-system
spec:
  template:
    metadata:
      labels:
        app: openpitrix
        component: openpitrix-upgrade-job
    spec:
      serviceAccountName: d3os
      restartPolicy: Never
      containers:
        - name: upgrade
          command:
            - start-jobs
          image: 139.198.9.238:30002/library/openpitrix-jobs
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/d3os
              name: d3os-config
      volumes:
        - name: d3os-config
          configMap:
            name: d3os-config